### ISSUE TITLE
StringIO to io in transliterate.py for Python3

### ISSUE THREAD

**Issue by TrigonaMinima** [irshadbhat/csnli#2]
In Python3 ```StringIO``` was renamed to ```io```. Due to this ```transliterate.py``` gives error in Python 3.

**Comment by irshadbhat** [comment]
I did all the training and testing using `python2.7` only. Currently there is no official support for `python3+`. I recommend using `python2.7` for now. I will update the codes for `python3+` support soon.

**Comment by TrigonaMinima** [comment]
I have only used the trained models yet, but ```three_step_decoding.py``` works perfectly in interpreter once you change the ```StringIO``` line.

I'll be going through your code, If you need any help for Python 3 support let me know.
